SessionPlanner.WebMVC/Controllers/SessionTypeController.cs
using Microsoft.AspNet.Identity;
using SessionPlanner.Models;
using SessionPlanner.Models.SessionType;
using SessionPlanner.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SessionPlanner.WebMVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SessionTypeController : Controller
    {
        // GET: List of SessionType
        public ActionResult Index()
        {
            var service = new SessionTypeService();
            var model = service.GetSessionTypes();

            return View(model);
        }

        // CREATE
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SessionTypeCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = new SessionTypeService();
            if(service.CreateSessionType(model))
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Session type could not be added");
            return View(model);
        }


        //Edit by Id
        public ActionResult Edit(int id)
        {
            var service = new SessionTypeService();
            var detail = service.GetSessionTypeByID(id);

            var model = new SessionTypeEdit
            {
                SessionTypeID = detail.SessionTypeID,
                Name = detail.Name,
                PricePerHour = detail.PricePerHour
            };

            var sessionService = new SessionTypeService();
            var sessionTypeList = sessionService.GetSessionTypes();

            ViewBag.SessionTypeID = new SelectList(sessionTypeList, "SessionTypeID", "Name", model.SessionTypeID);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SessionTypeEdit model)
        {
            var sessionService = new SessionTypeService();
            var sessionTypeList = sessionService.GetSessionTypes();

            ViewBag.SessionTypeID = new SelectList(sessionTypeList, "SessionTypeID", "Name", model.SessionTypeID);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = new SessionTypeService();

            if (service.EditSessionType(model))
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Session type could not be updated.");
            return View(model);
        }



        //DELETE by ID
        public ActionResult Delete(int id)
        {
            var service = new SessionTypeService();

            var model = service.GetSessionTypeByID(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteSessionType(int id)
        {
            var service = new SessionTypeService();

            if (service.DeleteSessionType(id))
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Delete", new { id });
        }




        //GET DETAILS by ID
        public ActionResult Details (int id)
        {
            var service = new SessionTypeService();
            var model = service.GetSessionTypeByID(id);

            return View(model);
        }

    }
}

SessionPlanner.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Safari Studios</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-custom navbar-fixed-top py-0">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Safari Studios", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Studio", "Studio", "Home")</li>
                    <li>@Html.ActionLink("Booking", "Index", "Session")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @Html.Partial("_UserPartial")
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer class="footer">
            <hr />
            <p>&copy; @DateTime.Now.Year - Safari Studios</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SessionPlanner.WebMVC/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNet.Identity
@if (User.IsInRole("Admin"))
{
    
        <li>@Html.ActionLink("User Management", "SeeAllUsers", "Manage")</li>
        <li>@Html.ActionLink("Session Management", "Index", "SessionType")</li>
    
    
}
else
{
    
}